### ISSUE TITLE
Beam c/s visualization

### ISSUE THREAD

**Issue by abhijeet-pandey** [jgwagenfeld/TUBA_V2#5]
I just want to check more about the TUBA_V2 which was not clear from the documentation. I am using Salome meca. I am using 1D beam for my project. Would TUBA_V2 help me visualize cross-sectional results such as stress along the depth of the beam event for a 1D beam mesh simulation?

**Comment by jgwagenfeld** [comment]
Do I understand you correctly, you want a vizualisation in radial and not axial direction? First, you would need TUYAU-elements for pipes or multi-fiber beams for beam - otherwise your elemnts are as you already mentioned only 1D and no crosssectional information exists.
For the above mentioned elements,  this functionality exists in an early stage in Code Aster but hasn't been implemented in TUBA.
